all:
	javac Alarm.java
	javac Audio.java
	javac BooleanEventListener.java
	javac Playlist.java 
	javac ScheduledAlarms.java 
	javac ScheduledPlay.java
	javac MusicHome.java -cp ./jl1.0.1.jar
	javac MusicPlayer.java -cp ./jl1.0.1.jar
	